# Generated by Django 3.2.5 on 2021-08-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('details', models.CharField(max_length=200, verbose_name='Details')),
                ('due_date', models.DateTimeField(verbose_name='Deadline')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('date_finished', models.DateTimeField(verbose_name='Completion Date')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
